# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quancode < Formula
  desc "Unified CLI orchestrator for AI coding agents"
  homepage "https://github.com/qq418716640/quancode"
  version "0.4.17"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qq418716640/quancode/releases/download/v0.4.17/quancode_0.4.17_darwin_amd64.tar.gz"
      sha256 "f332e1f138f31d6314f6729d9bf3f9c9b161ce44177cff70db5eb90df197f755"

      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qq418716640/quancode/releases/download/v0.4.17/quancode_0.4.17_darwin_arm64.tar.gz"
      sha256 "f4afd2592e10f6d90bb0a642a669cd7529e4b9f014876737d69640b915e40f14"

      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qq418716640/quancode/releases/download/v0.4.17/quancode_0.4.17_linux_amd64.tar.gz"
      sha256 "b2916a9b83f7ab0402e78d195bc5c4da6cc33eb6df11ba300f307f1702d40ffa"
      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qq418716640/quancode/releases/download/v0.4.17/quancode_0.4.17_linux_arm64.tar.gz"
      sha256 "ad2d0f0bda7b1de68dd6a75e67eee1ac649713bf0ce3a1b2d3422d4dec757e23"
      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
  end

  test do
    system "#{bin}/quancode", "version"
  end
end
