# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quancode < Formula
  desc "Unified CLI orchestrator for AI coding agents"
  homepage "https://github.com/qq418716640/quancode"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qq418716640/quancode/releases/download/v0.7.2/quancode_0.7.2_darwin_amd64.tar.gz"
      sha256 "499a3dafb703da76d4f5c34f716c6aa270593b3027bdc68d6054bfcd3c2cbf12"

      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qq418716640/quancode/releases/download/v0.7.2/quancode_0.7.2_darwin_arm64.tar.gz"
      sha256 "ebb9dcb25383d6d102a87b13c73f9af4c4e4902990bcc89b3ff15255d85d19d1"

      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qq418716640/quancode/releases/download/v0.7.2/quancode_0.7.2_linux_amd64.tar.gz"
      sha256 "5b419defbb7f381033c4403b1167a1e9f89add7d41cd655aea247290b28ce484"
      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qq418716640/quancode/releases/download/v0.7.2/quancode_0.7.2_linux_arm64.tar.gz"
      sha256 "e31abacdf365b806d513cd46e896fab99deddec8fca73b907854454b954e417f"
      define_method(:install) do
        bin.install "quancode"
        generate_completions_from_executable(bin/"quancode", "completion")
      end
    end
  end

  test do
    system "#{bin}/quancode", "version"
  end
end
